version: 2

updates:
  - package-ecosystem: "bundler"
    vendor: true
    directory: "/"
    labels:
      - dependencies
      - ruby
      - risk:low
    schedule:
      interval: "monthly"
    reviewers:
      - "zendesk/productivity-deploy"
    open-pull-requests-limit: 10
