---
name: Check risk
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  check-risk:
    runs-on: [ubuntu-latest]
    name: Check risk
    steps:
      - run: apt-get update && apt-get install -y ruby
      - uses: zendesk/check-risk-label@main
