---
name: Check risk
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  check-risk:
    runs-on: [ubuntu-latest]
    name: Check risk
    steps:
      - run: ruby -v || true
      - run: sudo apt-get update && sudo apt-get install -y ruby
      - uses: zendesk/check-risk-label@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
