name: Name Of Workflow One
on:
  - pull_request
  - pull_request_target
jobs:
  dump:
    name: Dump
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/enterprise-server@3.2/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - id: env and event
        run: env && echo && cat "$GITHUB_EVENT_PATH"
