name: Test

on: push

jobs:
  test:
    name: rubocop and rspec
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1.48.0
        with:
          bundler-cache: true
      - run: bundle exec rubocop && bundle exec rspec -f d
